apiVersion: v1
kind: Namespace
metadata:
  name: asdasdas-dev
  labels:
    environment-id: env_c6938909-b3eb-4bf1-9a97-0bfe77fc6c81
    project-id: project_4e46624b-e3fb-453d-8131-f29b32c691bd
    project-name: asdasdas
    environment-name: dev
    organization-id: org_99bfadb5-996a-47d5-a5fc-442c14a28627
