apiVersion: v1
kind: Namespace
metadata:
  name: fgddfghdfg-dev
  labels:
    environment-id: env_7259cccc-73ac-43ad-9512-570773de579a
    project-id: project_8201c9cb-ac14-4a67-a4b8-a7b25372d358
    project-name: fgddfghdfg
    environment-name: dev
    organization-id: org_99bfadb5-996a-47d5-a5fc-442c14a28627
